title: "Fatih Arslan"
url: "http://blog.arsln.org"
# url: "http://localhost:4000"
author: "Fatih Arslan"
email: "blog@arsln.org"
description: "Yekpare zamanın parçalanmaz anıları..."

auto: true
paginate: 4
paginate_files:
 - index.html

#permalink: /:year/:month/:day/:title
permalink: /:title/
markdown: rdiscount
pygments: true

exclude:
 - README.markdown
 - _drafts

